### ISSUE TITLE
Tracking issue for Welcome Page

### ISSUE THREAD

**Issue by usadson** [usadson/uffice#4]
Having a good user interface is key to providing a good user experience for office applications. A welcome page lets the user get back on track with their work.

- [ ] Opens on start up when no document is specified
- [ ] Lists recent documents, sorted by most recent to least recent
- [ ] Shows a button for creating new documents

## Windows-specific
- [ ] Integrates with cloud services on Windows 10, version 1709. See the [Cloud Filter API](https://learn.microsoft.com/en-us/windows/win32/api/_cloudapi/) specification on Microsoft Learn
- [ ] If (legally) possible, integrate with Microsoft 365/Office collaboration API
